### ISSUE TITLE
Add domains from command line or config file

### ISSUE THREAD

**Issue by dsazup** [robgordon89/local#2]
Would be nice if there could either be some config ~/.somefile.yaml (or whatever) where you have

```yaml
domains:
  - domain: app.test
     ip: 127.0.0.1
     host: blah.com
```

and you run `reload` or you do something like `cmd domain app.test --ip=127.0.0.1 --host=blah.com`

and it sets up caddyfile automatically
